language: c++
os:
  - linux
  - osx
dist: trusty
sudo: true

install:
  - bash ./install_dependencies.sh
cache:
  ccache: true
  directories:
    - $DEPS_DIR

script:
  - export DEPS_DIR=$(pwd)/deps
  - export SDK_DIR=$DEPS_DIR/SDK
  - if [ $TRAVIS_OS_NAME == linux ] then export CC=gcc-4.9 && export CXX=g++-4.9; fi
  - mkdir build
  - cmake -DXSDK_DIR=$SDK_DIR -G "Unix Makefiles" ./
  - make all -j4
