language: c++
os:
  - osx
dist: trusty
sudo: true

install:
  - bash ./install_dependencies.sh
cache:
  ccache: true
  directories:
    - ./deps

script:
  - export DEPS_DIR=$(pwd)/deps
  - export SDK_DIR=$DEPS_DIR/SDK
  - if [ $TRAVIS_OS_NAME == linux ]; then export CC=gcc-4.9 && export CXX=g++-4.9; fi
  - cmake -DXSDK_DIR=$SDK_DIR -G "Unix Makefiles" ./
  - make all -j4
